### ISSUE TITLE
add example with csv table sealevel input

### ISSUE THREAD

**Issue by jhidding** [MindTheGap-ERC/CarboKitten.jl#14]

**Comment by EmiliaJarochowska** [comment]
This was effectively moved to a different repo, https://github.com/MindTheGap-ERC/ck-triangle and will be taken care of by @xyl96 , so can be closed?

**Comment by xyl96** [comment]
I think now it's cleaned?

**Comment by jhidding** [comment]
The file @EmiliaJarochowska added has no time axis, nor any information on units, leave alone a source or citation.
