### ISSUE TITLE
Remove exporting visualisation so that CarboKitten loads up faster 

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/CarboKitten.jl#17]
Currently importing CarboKitten loads up plotting dependencies, which takes long, especially the first time.
Skip exporting plotting as default so it can be imported when user intentionally wants to plot.

- [x] migrate dependencies to separate work environment
- [x] update documentation
- [x] update scripts to generate figures

**Comment by jhidding** [comment]
Created a separate `workenv` where all the big dependencies for interactive use go. Now CarboKitten itself only depends on HDF5 and Transducers. Still need to update documentation and Makefile though.

One snatch: if you work in a different branch, you need to tell `workenv` that you want to use that branch of CarboKitten.

Anyway: just running CarboKitten itself (and generating the HDF5 files) should be much snappier now. Another way to make things a bit better is to create an executable image including some of the heftier plotting dependencies (see: https://docs.julialang.org/en/v1/devdocs/sysimg/).

**Comment by HannoSpreeuw** [comment]
> One snatch: if you work in a different branch, you need to tell `workenv` that you want to use that branch of CarboKitten.

I would vote against adding this complexity. This project has a substantial number of abstraction layers already, so hard enough for first time users.

**Comment by jhidding** [comment]
I have added `CairoMakie` under `[weakdeps]` and made the `CarboKitten.Visualization` submodule such that it only produces figures when `CairoMakie` is imported, otherwise it'll print a friendly message.
