### ISSUE TITLE
Add units

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/CarboKitten.jl#18]
The parameters, outputs and plots should keep track of units. How to do it? Discuss with @jhidding 

- [x] find the recommended way to do this in Julia
- [x] document the choice of units in the code and stick to them
- [x] implement thin layer to convert unitful config into model units

**Comment by jhidding** [comment]
Found this: https://github.com/PainterQubits/Unitful.jl

**Comment by EmiliaJarochowska** [comment]
Looks good, if a bit big-ish. More dependencies to precompile 😅

**Comment by jhidding** [comment]
my choice for model units would boil down to:

- time (Myr) gives simulation times that go roughly from t=0 to on the order of unity.
- length (m), in many plots we see meters being used for depth and km for distance, inside the model it is highly inconvenient to account for that, so we should stick to meters for everything (including sea level)
- the quoted unit for light intensity seems to be $\muE / m^2 / s$, but I can't seem to find what $\muE$ means. Elsewhere (on the interwebs) values are given in $W / m^2$.

**Comment by EmiliaJarochowska** [comment]
E is a historically important unit, if obsolete now: https://en.wikipedia.org/wiki/Einstein_(unit)

**Comment by EmiliaJarochowska** [comment]
Looks good. Obviously Einstein sounds more fancy than Watt but the latter is indeed more handy and we should stick to SI. Myr is on the longer end of scales we're looking at but probably the best choice.

**Comment by EmiliaJarochowska** [comment]
Rescale the facies to W/m^2

**Comment by jhidding** [comment]
I think this is done now; reopen if you disagree
