### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by HannoSpreeuw** [MindTheGap-ERC/CarboKitten.jl#22]
Unit tests and/or regression tests are pivotal to make sure we don't break anything when we modify code.

It should be triggered by GH Actions.

**Comment by HannoSpreeuw** [comment]
A template for automated building and testing for Julia code [does not seem to be available](https://docs.github.com/en/actions/automating-builds-and-tests), so we have to compile something ourselves or grab it from the web.

**Comment by jhidding** [comment]
Howto: https://github.com/julia-actions/julia-runtest

**Comment by jhidding** [comment]
To be clear, testing is already setup, we just need to enable CI here.

**Comment by HannoSpreeuw** [comment]
I see a test directory in the [feature-units branch](https://github.com/MindTheGap-ERC/CarboKitten.jl/tree/feature-units) but strangely enough not in main.

**Comment by HannoSpreeuw** [comment]
CI should be working now, through PR #35 and [this commit](https://github.com/MindTheGap-ERC/CarboKitten.jl/pull/35/commits/031f933089edda549f317dc81704f2894c2ee163).
