### ISSUE TITLE
Wrong operator in CaProd.jl?

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/CarboKitten.jl#24]
When using the branch `xy_test` I cannot precompile CarboKitten, because of [the following line](https://github.com/MindTheGap-ERC/CarboKitten.jl/blob/dcdf0f6afb092ff06d6a7640514ea9e92d9380e9/src/CaProd.jl#L110):

```
ERROR: LoadError: ParseError:
# Error @ /Users/emilia/Documents/Documents - UU101746/GitHub/CarboKitten/src/CaProd.jl:110:17
        s.height .+= Δ.denudation .* input.Δt  #number already in kyr
        s.height ._= Δ.redistribution .* input.Δt
#               ╙ ── whitespace is not allowed here
```

I don't recognize the `_` operator, there is no `?_` entry. You probably mean `-`?

**Comment by EmiliaJarochowska** [comment]
I was curious if it was the only issue so I re-ran it with `-` instead of `_` but I still got the error `Package CarboKitten does not have PhysicalErosion in its dependencies`. I added `include("./PhysicalErosion.jl")` to CarboKitten.jl and ran `Pkg.resolve()` but that gave me the following:

```
ERROR: Unsatisfiable requirements detected for package StableHashTraits [c5dd0088]:
 StableHashTraits [c5dd0088] log:
 ├─possible versions are: 0.1.1-1.1.6 or uninstalled
 ├─restricted to versions 1.1.3 by an explicit requirement, leaving only versions: 1.1.3
 └─restricted by julia compatibility requirements to versions: 1.1.5-1.1.6 or uninstalled — no versions left
```

I think the changes above are needed anyways, but I'm not going to PR because I can't check if it works without fixing the problem with `StableHashTraits`

**Comment by xyl96** [comment]
Yes I know, I have already changed it in my computer and I haven't pushed
it yet

**Comment by xyl96** [comment]
I currently don't have the physical erosion issue. But I have to admit that the visulisation is a conflict.

**Comment by EmiliaJarochowska** [comment]
@xyl96 can you confirm that this issue is resolved in your branch?

**Comment by EmiliaJarochowska** [comment]
Hello is anybody here?

**Comment by xyl96** [comment]
> Hello is anybody here?

yes.

**Comment by EmiliaJarochowska** [comment]
Is this issue resolved? I'm getting lost in all the issues and branches here ;-)

**Comment by xyl96** [comment]
> Is this issue resolved? I'm getting lost in all the issues and branches here ;-)

yes, because I haven't met this on my computer this time.
