### ISSUE TITLE
optimize lack of redistribution in some denudation models

### ISSUE THREAD

**Issue by jhidding** [MindTheGap-ERC/CarboKitten.jl#50]
the `redistribution` function now returns zero arrays which is a waste of energy.

possible solutions: 
- return nothing instead, and deal with those in the model code
- redesign so that redistribution is never called on these models

**Comment by xyl96** [comment]
Have done this. Do I need to add a test for this and make sure when it encounters `nothing` it's indeed not assigning space for `nothing`?

**Comment by jhidding** [comment]
Let's look at that tomorrow. I'll be in the office.

**Comment by jhidding** [comment]
Btw, I can't see your solution. Could you create a branch and PR? You can use the button 'develop' here on the right.

**Comment by xyl96** [comment]
> Btw, I can't see your solution. Could you create a branch and PR? You can use the button 'develop' here on the right.
> 
> No matter, found it!

I created a branch called issue/50, should I PR rn?
