### ISSUE TITLE
Improve documentation for Empirical denudation

### ISSUE THREAD

**Issue by jhidding** [MindTheGap-ERC/CarboKitten.jl#57]
- [x] reintegrate entangled docs
- [x] make sure we have permission to reuse figures and put them in the repository, replace the links to github assets.
- [x] document the implementation (or rather the motivation behind it)
- [x] document the source of the magic constants

**Comment by afreisz** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by xyl96** [comment]
I now showed the compiled data (I compile it by myself) insetad of snipping figures from literatures. Also I get confused about pandoc citation syntax, so I still use doi to cite the literatures.
