### ISSUE TITLE
Visualization mega issue

### ISSUE THREAD

**Issue by jhidding** [MindTheGap-ERC/CarboKitten.jl#7]
- [x] Improve crosssection coloring
- [x] Implement Wheeler diagram
- [ ] Create live updating plots
- [x] ~~Try `stratigraph` Python module~~
- [x] age-depth diagram with crosssection colorbar

**Comment by EmiliaJarochowska** [comment]
Is plotting of BS92 separate from the rest of CarboKitten? If yes, perhaps worth discussing if it is worth to work on two visualizations in parallel?

**Comment by EmiliaJarochowska** [comment]
Wheeler diagram: model time is on y axis
See https://www.sciencedirect.com/science/article/pii/S0012825224000333
