### ISSUE TITLE
Urgent fixes before presenting

### ISSUE THREAD

**Issue by jhidding** [MindTheGap-ERC/CarboKitten.jl#83]
Some urgent fixes:

- [x] rename ALCAP2 to ALCAP
- [x] rename `bedrock_elevation` to `initial_topography`
- [x] rename `run` to `run_model`
- [x] choose a set of convenient top-level exports
- [ ] document those exports
- [x] implement `read_column`
- [x] have `run_model` return the hdf5 filename

@EmiliaJarochowska did I forget anything?

**Comment by EmiliaJarochowska** [comment]
Thanks, looks great. I think this is enough :-)
