### ISSUE TITLE
Include transport based on shear stress

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/CarboKitten.jl#9]
This is for discussion. 

We follow the description of the transport in CARBONATE 3D.

# Shear stress

In this model, sediment is entrained (lifted from the surface and transported) if the shear stress $\tau$ exceeds the critical shear stress $\tau_{e}$.

The shear stress acting on the sediment $\tau_{total}$ can be simplified to a combination of shear stress from currents, waves and slopes:

$\tau_{total} = \tau_{current} + \tau_{wave} + \tau_{slope}$

## Shear stress due to slope

$\tau_{slope} = \Delta \rho g D \sin( \alpha ) ( \underline{G} )/G$

$\Delta \rho$ is excess density of the sediment, *g* is gravitational acceleration, *D* is grain size and $\alpha$ the max slope angle parallel to the gradient vector $\underline{G}$.

![Eq 17](https://github.com/MindTheGap-ERC/CarboKitten/assets/18270548/47d9ba18-0431-4286-8f94-00210b987e1e)

## Shear stress due to wave and currents

This can be simplified to a unidirectional shear stress vector field where the shear stress decreases with depth in a similar way as the production rate $D_{0}$.

$\tau_{wave/current} = \tau_{wave/current}(z)$

![Fig 1](https://github.com/MindTheGap-ERC/CarboKitten/assets/18270548/30790c25-5174-4dd4-ae0e-b555eaa7c4a1)

The depth-dependence function is defined piecewise between water surface and two parameter depths $z_{t}$ and $z_{b}$.
Note that this production curve is different from the one we use from Bosscher and Schlager (1992).  

## Shear stress is different for different sediment types

Different grain sizes have different critical shear stress $\tau_{e}$. Each lithofacies corresponds to different sediment producers and that translates into different grain size distributions. For example, corals build massive skeletons that form wave-resistant reefs and they disintegrate into coarse rubble. Algae that live in lagoons disintegrate into mud.

CARBONATE 3D simplifies the range of grain sizes into two: *grains* and *matrix*, which means: medium grains (2 mm and larger) and mud (a liberal definition: grains < 2 mm). Each lithofacies will disintegrate into its specific distribution of these two fractions. For example, the reef facies would produce 70% of grains and 30% of matrix and the lagoon facies 100% matrix. This requires each grid cell to have an attribute describing its sediment composition.

For a given sediment type, critical shear stress can be approximated with:

$\tau_{e} = \Delta \rho g D \sin( \alpha_{c} )$

Where $\alpha_{c}$ is the angle of repose. There are other methods based on empirical properties of different sediment types, but they are subject to various constraints discussed in Warrlich, Waltham, and Bosence (2002) p. 384-385.

# Transport

When described as function of shear stress, transport starts when $|\tau_{total}| > \tau_{e}$ for a given sediment type and stops when $|\tau_{total}| = \tau_{e}$.

Deposition rate is proportional to sediment load *L*:

$L = L_{0}e^{-(S-S_{d}/X)}$

$L_{0}$ is the initially entrained sediment load, *X* the characteristic transport distance (user input) and $S_{d}$ is the point along the path *S* where sedimentation starts.

Further details on calculating transport direction are provided in the thesis Warrlich (2000) and we know that Georg used a separate array for calculating it, this is not documented in detail, but it's possible to ask him.

# Sediment available for transport

After deposition, sediment (loose) turns into rock (solid) through the process of diagenesis. So it is only available for transport for a limited time: either directly after it had been deposited or after it had been made available from rock through disintegration. 

CARBONATE 3D uses the following order of steps (ignore anything referring to "clastic sediments"):

![flowchart](https://github.com/MindTheGap-ERC/CarboKitten/assets/18270548/e4d2a81c-7c69-432f-8371-fecd308c934a)

It is not clear to me why entrainment of disintegrated sediment precedes the production of new sediment. One might consider that disintegration acts upon rock exposed after loose sediment is entrained completely. So if in any grid cell sediment is produced and then completely removed, then this grid cell can be subject to disintegration and further sediment removal. Something like this:

1. Production leads to new loose sediment
2. Loose sediment is transported
2. In grid cells where no production took place or in which all new sediment has been removed, disintegration occurs, which also leads to new loose sediment
3. Loose sediment is transported

That also means transport calculated twice. Perhaps we could ask Georg about it.

## Disintegration

Only disintegration through hydrodynamic (wave and current) and biological activity is included. The thesis by Warrlich (2000) included disintegration as a result of oversteepening of depositional slopes, but this has been abandoned in the Warrlich, Waltham, and Bosence (2002) paper. Possibly because sediment transport in each step prevents from oversteepened sloped forming in the first place. We follow the paper and ignore it here.

Disintegration rate *B* is modeled similarly to production rate:

![disintegration](https://github.com/MindTheGap-ERC/CarboKitten/assets/18270548/0d50309b-fea9-48c0-8831-db8fc1835f87)
The article by Warrlich, Waltham, and Bosence (2002) includes a correcting factor $U_{E}(x,y)$ that reflects the proximity to open water. This can probably be omitted initially.

Values of parameters listed here are in Fig. 4.4 p. 39-40 of Warrlich (2000).

This is based on following references:

Bosscher, Hemmo, and Wolfgang Schlager. 1992. “Computer Simulation of Reef Growth.” Sedimentology 39 (3): 503–12. https://doi.org/https://doi.org/10.1111/j.1365-3091.1992.tb02130.x.

Warrlich, G. M. D. 2000. “3D Computer Forward Modelling of Carbonate Platform Evolution.” {PhD}, London: Royal Holloway University of London.

Warrlich, G. M. D., D. A. Waltham, and D. W. J. Bosence. 2002. “Quantifying the Sequence Stratigraphy and Drowning Mechanisms of Atolls Using a New 3‐D Forward Stratigraphic Modelling Program (CARBONATE 3D).” Basin Research 14 (3): 379–400. https://doi.org/10.1046/j.1365-2117.2002.00181.x.

Sadly Markdown support here does not extend to BibTex ;-) And two equations are not rendered properly for some reason.

**Comment by jhidding** [comment]
thanks, you score points for most awesome feature request/issue ever 😉

**Comment by EmiliaJarochowska** [comment]
Notes from discussion yesterday:
![IMG_7604 2](https://github.com/MindTheGap-ERC/CarboKitten.jl/assets/18270548/b63641d6-d3b5-49ff-9c2b-4028a16c1607)

**Comment by EmiliaJarochowska** [comment]
@jhidding was looking for the definition of excess density.
We have a parameter file for CARBONATE 3D and the line there says:

excessDensity | = | 1500 |   | Excess density of the sediment   [kg/m^3]
-- | -- | -- | -- | --

This allows us to double check if it is indeed the difference between the grain density and seawater density:
$\rho_{sw}$ = [1020 kg/m³](https://en.wikipedia.org/wiki/Seawater#Density)
$\rho_{calcite}$ = [2 711 kg/m³](https://www.aqua-calc.com/page/density-table/substance/calcium-blank-carbonate)
$\Delta_{\rho}$ = 1691 kg/m³
Which makes sense, given that not all grains will be solid calcite so on average a grain's density will be lower.

**Comment by jhidding** [comment]
I actually was implementing this where $\Delta_{\rho}$ is dependent on the facies. Is that too much of a complication?

**Comment by EmiliaJarochowska** [comment]
Further down the line (we haven't even started it) we wanted to introduce aragonite and calcite as components of the sediment (to allow coupling with the infamous diagenetic model). So a facies would have two possible minerals and thus two densities... But it is probably not handy to preempt it at this point?

**Comment by EmiliaJarochowska** [comment]
I think this issue can be closed now. Ok, @jhidding ?
